eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: projectD
  rabbitmq:
    host: 192.168.50.12
    username: admin
    password: admin
    port: 32491
    publisher-confirm-type: correlated